name: Update Tags Based on Commits

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-tags:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Get next version
        id: get_next_version
        uses: thenativeweb/get-next-version@2.6.0

      - name: Create and push tag
        if: steps.get_next_version.outputs.hasNextVersion == 'true'
        run: |
          version="v${{ steps.get_next_version.outputs.version }}"
          git tag -s "$version" -m "Release $version"
          git push origin "$version"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Notify on failure
        if: failure()
        run: |
          echo "Failed to update tags. Check the workflow logs for details."
